services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - .env

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql

  app:
    build: .
    container_name: flask-app
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    command: >
      sh -c "sleep 30 &&
             flask db upgrade &&
             flask seed &&
             python app.py"

  mcp_server:
    build: ./mcp_server/
    container_name: mcp_server
    ports:
      - "6000:6000"
    depends_on:
      - mysql
    env_file:
      - .env
